// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njmnwaiekqxpgfwmoyhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qbW53YWlla3F4cGdmd21veWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NzEzODQsImV4cCI6MjA3MDQ0NzM4NH0.WoAv8ziXSEGCz2-6IoF9t-gYDQCoAUvEhvu7fcyBbek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});